packages:
  github.com/authorhealth/events:
    config:
      all: true
      dir: "{{ .InterfaceDir }}"
      filename: "mock_{{ .InterfaceNameSnake }}.go"
      inpackage: true
      recursive: true
      with-expecter: true
resolve-type-alias: false
issue-845-fix: true
